# Form implementation generated from reading ui file 'BilderTest.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(757, 561)
        #--Scroll-Bereich--#
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(30, 30, 701, 501))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 699, 499))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        #--Scroll-Balken--#
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(670, 10, 16, 471))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        #--Bilder--#
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 101))
        self.label.setStyleSheet("Bilder/blackcruiser.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Bilder/blackcruiser.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 161, 101))
        self.label_2.setStyleSheet("Bilder/kisspng-clip-art-cruise-ship-portable-network-graphics-ima-cruise-ship-clipart-cute-9-13-x-13-dumielaux-5cd9dc01bffa83.4090745.jpg);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Bilder/kisspng-clip-art-cruise-ship-portable-network-graphics-ima-cruise-ship-clipart-cute-9-13-x-13-dumielaux-5cd9dc01bffa83.4090745.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(410, 20, 161, 101))
        self.label_3.setStyleSheet("Bilder/kreuzfahrtschiff-logo_74218-64.jpg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Bilder/kreuzfahrtschiff-logo_74218-64.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
