# Form implementation generated from reading ui file 'QT-Windows/ChangeWindowTest.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 781, 521))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.label = QtWidgets.QLabel(self.Home)
        self.label.setGeometry(QtCore.QRect(270, 200, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.Home)
        self.blue = QtWidgets.QWidget()
        self.blue.setStyleSheet("background-color: blue")
        self.blue.setObjectName("blue")
        self.stackedWidget.addWidget(self.blue)
        self.red = QtWidgets.QWidget()
        self.red.setStyleSheet("background-color: red")
        self.red.setObjectName("red")
        self.stackedWidget.addWidget(self.red)
        self.yellow = QtWidgets.QWidget()
        self.yellow.setStyleSheet("background-color: yellow")
        self.yellow.setObjectName("yellow")
        self.stackedWidget.addWidget(self.yellow)
        self.blue_btn = QtWidgets.QPushButton(self.centralwidget)
        self.blue_btn.setGeometry(QtCore.QRect(470, 550, 75, 23))
        self.blue_btn.setObjectName("blue_btn")
        self.red_btn = QtWidgets.QPushButton(self.centralwidget)
        self.red_btn.setGeometry(QtCore.QRect(560, 550, 75, 23))
        self.red_btn.setObjectName("red_btn")
        self.yell_btn = QtWidgets.QPushButton(self.centralwidget)
        self.yell_btn.setGeometry(QtCore.QRect(650, 550, 75, 23))
        self.yell_btn.setObjectName("yell_btn")
        self.home_btn = QtWidgets.QPushButton(self.centralwidget)
        self.home_btn.setGeometry(QtCore.QRect(30, 550, 75, 23))
        self.home_btn.setObjectName("home_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "please click the buttons below"))
        self.blue_btn.setText(_translate("MainWindow", "blue"))
        self.red_btn.setText(_translate("MainWindow", "red"))
        self.yell_btn.setText(_translate("MainWindow", "yellow"))
        self.home_btn.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
