# Form implementation generated from reading ui file 'NeuesHauptmenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CBOrt = QtWidgets.QComboBox(self.centralwidget)
        self.CBOrt.setGeometry(QtCore.QRect(250, 20, 231, 41))
        self.CBOrt.setObjectName("CBOrt")
        self.CBOrt.addItem("")
        self.CBOrt.addItem("")
        self.CBOrt.addItem("")
        self.CBOrt.addItem("")
        self.CBPersonen = QtWidgets.QComboBox(self.centralwidget)
        self.CBPersonen.setGeometry(QtCore.QRect(490, 20, 231, 41))
        self.CBPersonen.setObjectName("CBPersonen")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(730, 20, 51, 41))
        self.SearchButton.setObjectName("SearchButton")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(10, 20, 231, 41))
        self.dateEdit_2.setObjectName("dateEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CBOrt.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.CBOrt.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.CBOrt.setItemText(0, _translate("MainWindow", "Bitte Auswählen", "True"))
        self.CBOrt.setItemText(1, _translate("MainWindow", "Ostsee"))
        self.CBOrt.setItemText(2, _translate("MainWindow", "Nordsee"))
        self.CBOrt.setItemText(3, _translate("MainWindow", "Mittelmeer"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))
        self.show()

app = QApplication(sys.argv)
w = Ui_MainWindow()           #Fenster aufbauen (!= Fenster anzeigen)
sys.exit(app.exec_())   #Python Programm stoppt wenn Fenster geschlossen wird
