# Form implementation generated from reading ui file 'NeuesHauptmenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.CBOrt = QtWidgets.QComboBox(self.centralwidget)
        self.CBOrt.setGeometry(QtCore.QRect(250, 20, 231, 41))
        self.CBOrt.setObjectName("CBOrt")
        self.CBOrt.addItem("")
        self.CBOrt.addItem("")
        self.CBOrt.addItem("")
        self.CBOrt.addItem("")

        self.CBPersonen = QtWidgets.QComboBox(self.centralwidget)
        self.CBPersonen.setGeometry(QtCore.QRect(490, 20, 231, 41))
        self.CBPersonen.setObjectName("CBPersonen")
        self.CBPersonen.addItem("")
        self.CBPersonen.addItem("")
        self.CBPersonen.addItem("")
        self.CBPersonen.addItem("")
        self.CBPersonen.addItem("")
        self.CBPersonen.addItem("")
        self.CBPersonen.addItem("")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(730, 20, 51, 41))
        self.SearchButton.setObjectName("SearchButton")
        #button = self.SearchButton

        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(10, 20, 231, 41))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_2.setDateTime(QtCore.QDateTime.currentDateTime()) # Derzeitiges Datum als Voreinstellung
        self.dateEdit_2 = QtWidgets.QDateEdit(calendarPopup=True)   # Calendar popd auf beim anklicken


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # creating label to display input
        #self.label = QLabel(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CBOrt.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.CBOrt.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.CBOrt.setItemText(0, _translate("MainWindow", "Bitte Auswählen", "True"))
        self.CBOrt.setItemText(1, _translate("MainWindow", "Ostsee"))
        self.CBOrt.setItemText(2, _translate("MainWindow", "Nordsee"))
        self.CBOrt.setItemText(3, _translate("MainWindow", "Mittelmeer"))
        self.CBPersonen.setItemText(0, _translate("MainWindow", "2 Personen"))
        self.CBPersonen.setItemText(1, _translate("MainWindow", "3 Personen"))
        self.CBPersonen.setItemText(2, _translate("MainWindow", "4 Personen"))
        self.CBPersonen.setItemText(3, _translate("MainWindow", "5 Personen"))
        self.CBPersonen.setItemText(4, _translate("MainWindow", "6 Personen"))
        self.CBPersonen.setItemText(5, _translate("MainWindow", "7 Personen"))
        self.CBPersonen.setItemText(6, _translate("MainWindow", "8 Personen"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))

        # adding action to button
        #button = SearchButton("", self)
        self.SearchButton.pressed.connect(self.Search)

    # define button action
    def Search(self):
        #datum = self.
        ort = self.CBOrt.currentText()
        personen = self.CBPersonen.currentText()

        # showing content on the screen though label
        #self.label.setText("Zeitraum: " + datum)
        self.label.setText("Reiseziel: " + ort)
        self.label.setText("Anzahl Personen: " + personen)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
